export const patientDetails = [
  'BIRTH DATE',
  'WEIGHT',
  'HEIGHT',
  'GENDER',
  'RACE',
  'SEXUAL ORIENTATION',
];

export const areas = [
  'HEALTH INSURANCE',
  'APPOINTMENT + CHECK UPS',
  'WEIGHT MANAGEMENT AND DIET',
  'PRESCRIPTION + MEDICATION',
  'MENTAL HEALTH + WELLNESS',
  'DESCRIMINATION + EQUITY',
  'DOCTOR RECOMMENDATIONS',
  'CHRONIC CONDITIONS',
];

export const profile = [
  'PERSONAL INFO',
  'REMINDER',
  'PHYSICIAN INFO',
  'MEDICATIONS',
  'DIET + PHYSICAL LIFESTYLE',
  'HEALTH JOURNAL',
  'HEALTH DISPARITIES',
  'FAMILY HISTORY',
];
